services:
  komga:
    image: gotson/komga:1.24.4
    container_name: komga_loadtest
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "6063:25600"
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ../../books
        target: /data/books
        read_only: true
    environment:
      - TZ=Etc/UTC
